[providers]
python = "3.11"
node = "18"

[phases.setup]
nixPkgs = ["python311", "nodejs_18", "imagemagick"]

[phases.install]
cmds = [
    "python -m venv venv",
    "venv/bin/pip install --upgrade pip",
    "venv/bin/pip install -r requirements.txt",
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run dev"